name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Arquivos criados
      id: arquivos-criados
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Arquivos criados
        setup-command: ''
        command: "./tests/arquivos_criados.sh"
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ARQUIVOS-CRIADOS_RESULTS: "${{steps.arquivos-criados.outputs.result}}"
      with:
        runners: arquivos-criados
